export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const CLEAR_CART = "CLEAR_CART";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
