export const REGISTER_REQUEST = "USERS_REQUEST";
export const REGISTER_SUCCESS = "USERS_SUCCESS";
export const REGISTER_FAIL = "USERS_FAIL";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";